[package]
name = "qdp-python"
version.workspace = true
edition.workspace = true

[lib]
name = "mahout_qdp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
qdp-core = { path = "../qdp-core" }
