[package]
name = "python"
version.workspace = true
edition.workspace = true

[lib]
name = "mahout"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["abi3-py311"] }
core = { path = "../core" }
cudarc = { workspace = true }
