[package]
name = "qdp-kernels"
version.workspace = true
edition.workspace = true

[dependencies]
cudarc = { workspace = true }

[build-dependencies]
cc = { workspace = true }

[lib]
name = "qdp_kernels"
crate-type = ["rlib", "staticlib"]
